# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '18.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AixExample' do
  config = use_native_modules!
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )


    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
      end

      # Fix cmark-gfm C module headers conflicting with Nitro C++ interop.
      # cmark-gfm uses `extern "C" { #include "cmark-gfm.h" }` which triggers
      # a C++ module import inside extern "C" when SWIFT_OBJC_INTEROP_MODE = objcxx.
      target.build_configurations.each do |config|
        flags = config.build_settings['OTHER_SWIFT_FLAGS'] || '$(inherited)'
        unless flags.include?('-Wno-module-import-in-extern-c')
          config.build_settings['OTHER_SWIFT_FLAGS'] = "#{flags} -Xcc -Wno-module-import-in-extern-c"
        end
      end
    end
  end
end
